### PR TITLE
Replace "&", "<", ">" to HTML entities in Markdown.

### PR DESCRIPTION
**Pull request by Milly**
More safely.

### CODE REVIEW

**Comment by xupefei** [comment]
I guess your patch will disable inline html tags in Markdown file.
Can you explain why it is safer?

**Comment by Milly** [comment]
Inline html tags are replaced in textarea that is data-store.
But `$("#text-input").val()` returns decoded value.

```html
<textarea id="text-input">Content &lt;b&gt;foobar&lt;/b&gt;.</textarea>
<script>
alert($("#text-input").val()); // => "Content <b>foobar</b>."
</script>
```

If markdown contains unexpected tag, It will break the base HTML in `md2html.html`.

```markdown
# Invalid markdown
</textarea> Close textarea
## Not visibel area
<script>document.body.innerHTML = "foobar";</script>
```

**Comment by xupefei** [comment]
Thanks for the explanation, I got it.
I found that the [`WebUtility.HtmlEncode`](https://msdn.microsoft.com/en-us/library/ee388364%28v=vs.110%29.aspx) function does exactly the same work as your patch. May you make a new commit for changing string replacement codes to `md = WebUtility.HtmlEncode(md);`, or I will do that for you while merging this patch?

**Comment by xupefei** [comment]
Hi, this PR is now merged. You may delete your fork safely.

**Pull request closed without merging**
